name: automatically publish chrome-types

on:
  workflow_dispatch:
  schedule:
    - cron: '15 22 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - run: npm ci

      - run: npm test

  publish-npm:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/

      - run: npm ci

      - run: npm run prepareChromeTypes

      # Log differences in the index.d.ts file.
      # (This will always have a "generated on" diff, but that's not included in the decision
      # as to whether to publish again).
      - run: diff -C1 bin/prepare-types/work/index.d.ts bin/prepare-types/work/old/index.d.ts

      # Log differences in the history.json file.
      # (This is written formatted nicely, so diffs are probably readable)
      - run: diff -C1 bin/prepare-types/work/history.json bin/prepare-types/work/old/history.json

      # This publishes only if the package.json version has been incremented compared to the latest
      # published version. Incrementing happens in the above prepareChromeTypes step.
      - uses: JS-DevTools/npm-publish@v1
        with:
          package: ./bin/prepare-types/work/package.json
          token: ${{ secrets.NPM_TOKEN }}
